root ::= query

query ::= "SELECT " attributes ws "FROM " tables (ws "WHERE " condition)? (ws "GROUP BY " attribute)? (ws "ORDER BY " order)? (ws "LIMIT " number)? (ws "OFFSET " number)? ";"

attribute ::= column | string

attributes ::= attribute attributes-rest

attributes-rest ::= ("," attribute attributes-rest)? 

table ::= TABLE_NAMES_PLACEHOLDER

column ::= (table ".")? column-name

column-name ::= COLUMN_NAMES_PLACEHOLDER

join ::= "JOIN " | "LEFT JOIN " | "RIGHT JOIN " | "FULL JOIN " | "INNER JOIN "

join-condition ::= attribute "=" attribute

tables ::= table tables-rest

tables-rest ::= (join ws table "ON " join-condition tables-rest)?

condition ::= condition-term condition-rest

condition-term ::= attribute "=" value | attribute "<" value | attribute ">" value | attribute "<=" value | attribute ">=" value | attribute "!=" value | attribute "LIKE " value | "(" condition ")" | attribute "IS " "NULL " | attribute "IS " "NOT " "NULL " | attribute "IN " "(" value ("," value)* ")"

condition-rest ::= ("AND " condition-term condition-rest | "OR " condition-term condition-rest)?

order ::= attribute ("ASC" | "DESC")?

value ::= string | number

string ::= [ \t!#-\[\]-~]* ws

number ::= ("-"? ([0-9] | [1-9] [0-9]*)) ("." [0-9]+)? ([eE] [-+]? [0-9]+)? ws

ws ::= [ \t\n]+